var department = document.getElementById("department");
var program = document.getElementById("program");
var major = document.getElementById("major");

var programs = {
  CBFS: [
    "ASSOCIATE IN BUILDING PROPERTY MANAGEMENT",
    "ASSOCIATE IN BUSINESS TECHNOLOGY",
    "ASSOCIATE IN BUSINESS TECHNOLOGY/TWO-YEAR JUNIOR SEC'L",
    "ASSOCIATE IN COMMERCE",
    "ASSOCIATE IN ENTREPRENEURSHIP",
    "ASSOCIATE IN OFFICE TECHNOLOGY MANAGEMENT",
    "ASSOCIATE IN SALES MANAGEMENT",
    "ASSOCIATE IN SALESMANSHIP",
    "ASSOCIATE IN SUPPLY MANAGEMENT",
    "BACHELOR OF SCIENCE IN ACCOUNTANCY",
    "BACHELOR OF SCIENCE IN ACCOUNTING TECHNOLOGY",
    "BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION ",
    "BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION",
    "BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION",
    "BACHELOR OF SCIENCE IN COMMERCE",
    "BACHELOR OF SCIENCE IN ENTREPRENEURIAL MANAGEMENT",
    "BACHELOR OF SCIENCE IN FINANCE",
    "BACHELOR OF SCIENCE IN FINANCIAL MANAGEMENT",
    "BACHELOR OF SCIENCE IN MANAGEMENT ACCOUNTING",
    "BACHELOR OF SCIENCE IN MARKETING MANAGEMENT",
    "BACHELOR OF SCIENCE IN OFFICE ADMINISTRATION",
    "BACHELOR OF SCIENCE IN OFFICE MANAGEMENT",
    "BACHELOR OF SCIENCE IN SECRETARIAL ADMINISTRATION",
    "CERTIFICATE IN APPLIED BUSINESS ENTREPRENEURSHIP",
    "CERTIFICATE IN COMPUTER SECRETARIAL",
    "CERTIFICATE IN SALESMANSHIP",
    "TWO-YEAR JUNIOR SECRETARIAL",
  ],
  CTHM: [
    "ASSOCIATE IN HOSPITAL MANAGEMENT",
    "ASSOCIATE IN HOTEL & RESTAURANT OPERATIONS",
    "BACHELOR IN INTERNATIONAL CULINARY MANAGEMENT",
    "BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT",
    "BACHELOR OF SCIENCE IN TOURISM MANAGEMENT",
    "BACHELOR OF SCIENCE IN TRAVEL TECHNOLOGY",
  ],
  IGS: [
    "BACHELOR OF ARTS IN POLITICAL SCIENCE",
    "BACHELOR OF SCIENCE IN MARKETING MGMT (EXEC PROG)",
    "BACHELOR OF SCIENCE IN MICRO-FINANCE (EXEC PROG)",
    "CERTIFICATE IN BARANGAY GOVERNANCE",
    "CERTIFICATE IN PUBLIC HEALTH & GOVERNANCE",
    "DIPLOMA IN DEVELOPMENT MANAGEMENT & GOVERNANCE",
    "DOCTOR IN EDUCATION",
    "DOCTOR OF PHILOSOPHY",
    "DOCTOR OF SCIENCE IN COMPLEMENTARY & ALTERNATIVE MEDICINE",
    "EXECUTIVE DOCTOR IN LEADERSHIP",
    "EXECUTIVE DOCTOR IN LEADERSHIP PUBLIC MANAGEMENT",
    "EXECUTIVE MASTER IN BUSINESS ADMINISTRATION",
    "GRADUATE CERTIFICATE IN INSTRUCTIONAL MEDIA & DESIGN",
    "MASTER IN ARTS IN EARLY CHILDHOOD EDUCATION",
    "MASTER IN ARTS IN EDUCATION",
    "MASTER IN ARTS IN INNOVATIVE IN ENGLISH EDUCATION",
    "MASTER IN ARTS IN INNOVATIVE IN FILIPINO EDUCATION",
    "MASTER IN ARTS IN INNOVATIVE IN GENERAL SCIENCE EDUCATION",
    "MASTER IN ARTS IN INNOVATIVE IN MATH EDUCATION",
    "MASTER IN ARTS IN INNOVATIVE IN PHYSICAL EDUCATION",
    "MASTER IN ARTS IN INNOVATIVE IN SOCIAL SCIENCE EDUCATION",
    "MASTER IN ARTS IN INNOVATIVE IN SPECIAL EDUCATION",
    "MASTER IN ARTS IN SPECIAL EDUCATION",
    "MASTER IN BUSINESS ADMINISTRATION",
    "MASTER IN BUSINESS ADMINISTRATION IN HUMAN RESOURCE MANAGEMENT",
    "MASTER IN BUSINESS ADMINISTRATION",
    "MASTER IN DEVELOPMENT MANAGEMENT & GOVERNANCE",
    "MASTER IN INFORMATION SYSTEMS",
    "MASTER IN INNOVATIVE TECHNOLOGY EDUCATION",
    "MASTER IN PUBLIC ADMINISTRATION",
    "MASTER IN PUBLIC ADMINISTRATION IN LOCAL GOVERNANCE",
    "MASTER OF ARTS IN COMPLEMENTARY & ALTERNATIVE MEDICINE",
    "MASTER OF ARTS IN NURSING",
    "MASTER OF SCIENCE IN RADIOLOGIC TECHNOLOGY",
    "POST BACCALAUREATE PROGRAM IN BUILDING MANAGEMENT",
    "POST BACCALAUREATE PROGRAM IN FIRE SAFETY",
  ],
  COS: [
    "BACHELOR OF ARTS",
    "BACHELOR OF SCIENCE",
    "BACHELOR OF SCIENCE IN BIOLOGY",
    "BACHELOR OF SCIENCE IN PSYCHOLOGY",
  ],
  COE: [
    "ASSOCIATE IN BUSINESS EDUCATION",
    "ASSOCIATE IN EDUCATION",
    "BACHELOR IN BUSINESS EDUCATION-SECRETARIAL EDUCATION",
    "BACHELOR IN SECONDARY EDUCATION",
    "BACHELOR OF SCIENCE IN EDUCATION MAJOR EARLY CHILDHOOD EDUCATION",
    "BACHELOR OF SCIENCE IN ELEMENTARY EDUCATION",
    "BACHELOR OF SCIENCE IN ELEMENTARY EDUCATION WITH SPECIALIZATION IN EARLY CHILDHOOD EDUCATION",
    "BACHELOR OF SCIENCE IN ELEMENTARY EDUCATION WITH TNG PRE-SCHOOL EDUCATION",
    "BACHELOR OF SCIENCE IN ELEMENTARY EDUCATION WITH TNG SPECIALIZATION EDUCATION",
    "CERTIFICATE OF TEACHING IN SPECIAL EDUCATION",
    "CERTIFICATE OF TEACHING",
    "CERTIFICATE OF TEACHING",
    "TEACHER CERTIFICATE PROGRAM",
  ],
  CCSCE: [
    "BACHELOR IN CIVIL ENGINEERING",
    "BACHELOR OF SCIENCE IN CIVIL ENGINEERING",
    "BACHELOR OF SCIENCE IN CONSTRUCTION ENGINEERING TECHNOLOGY",
    "CERTIFICATE IN CONSTRUCTION ESTIMATING",
    "DIPLOMA CONSTRUCTION ENGINEERING MANAGEMENT",
    "DIPLOMA CONSTRUCTION ENGINEERING TECHNOLOGY",
    "DIPLOMA IN CIVIL ENGINEERING TECHNOLOGY",
  ],
  IIT: [
    "AUTOMOTIVE (ONE YEAR PROGRAM)",
    "REF & AIRCON (ONE YEAR PROGRAM)",
    "ELECTRONICS (ONE YEAR PROGRAM)",
    "MACHINE SHOP (ONE YEAR PROGRAM)",
    "DIESEL MECHANICS (ONE YEAR PROGRAM)",
    "DRAFTING (ONE YEAR PROGRAM)",
    "DRESS MAKING (ONE YEAR PROGRAM)",
    "ASSOCIATE IN ELECTRONICS TECHNOLOGY",
    "ASSOCIATE IN ENGINEERING",
    "ASSOCIATE IN INDUSTRIAL TECHNOLOGY",
    "BACHELOR IN SPECIFIED INDUSTRIAL ENGINEERING",
    "BACHELOR OF SCIENCE IN AVIATION TECHNOLOGY",
    "BACHELOR OF SCIENCE IN BUILDING TECHNOLOGY MANAGEMENT",
    "BACHELOR OF SCIENCE IN CIVIL TECHNOLOGY",
    "BACHELOR OF SCIENCE IN CONSTRUCTION MANAGEMENT",
    "BACHELOR OF SCIENCE IN ELECTRICAL ENGINEERING",
    "BACHELOR OF SCIENCE IN ELECTRICAL TECHNOLOGY",
    "BACHELOR OF SCIENCE IN ELECTRONICS & TELECOMMUNICATION TECHNOLOGY",
    "BACHELOR OF SCIENCE IN INDUSTRIAL TECHNOLOGY",
    "BACHELOR OF SCIENCE IN TELECOMMUNICATIONS TECHNOLOGY",
    "BACHELOR OF SCIENCE IN COMPUTER ENGINEERING",
    "CERTIFICATE IN BUILDING MANAGEMENT",
    "CERTIFICATE IN BUILDING TECHNOLOGY MANAGEMENT",
    "CERTIFICATE IN INDUSTRIAL FACILITIES",
    "CERTIFICATE IN INDUSTRIAL TECHNOLOGY",
    "DIPLOMA IN ELECTRICAL TECHNOLOGY",
    "DIPLOMA IN INDUSTRIAL FACILITIES TECHNOLOGY",
    "DIPLOMA IN TELECOMMUNICATION ACCESS NETWORK TECHNOLOGY",
    "DIPLOMA IN TELECOMMUNICATION TECHNOLOGY",
  ],
  CCIS: [
    "ASSOCIATE IN APPLICATION DEVELOPMENT",
    "ASSOCIATE IN COMPUTER APPLICATIONS TECHNOLOGY",
    "ASSOCIATE IN COMPUTER NETWORK ADMINISTRATION",
    "ASSOCIATE IN COMPUTER TECHNOLOGY",
    "ASSOCIATE IN INFO TECHNOLOGY SERVICE MANAGEMENT",
    "ASSOCIATE IN MULTIMEDIA TECHNOLOGY",
    "BACHELOR IN COMPUTER SCIENCE",
    "BACHELOR OF SCIENCE IN COMPUTATIONAL & DATA SCIENCES",
    "BACHELOR OF SCIENCE IN COMPUTER NETWORK ADMINISTRATION",
    "BACHELOR OF SCIENCE IN COMPUTER SCIENCE",
    "BACHELOR OF SCIENCE IN COMPUTER TECHNOLOGY",
    "BACHELOR OF SCIENCE IN INDUSTRIAL TECHNOLOGY",
    "BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY",
    "CERTIFICATE IN COMPUTER TECHNICIAN",
    "CERTIFICATE IN INDUSTRIAL TECHNOLOGY",
    "CERTIFICATE IN WEB DESIGN",
    "CERTIFICATE ON COMPUTER TECHNOLOGY",
    "DIPLOMA IN APPLICATION DEVELOPMENT",
    "DIPLOMA IN COMPUTER NETWORK ADMINISTRATION",
  ],
  CGPP: ["BACHELOR OF ARTS IN  POLITICAL SCIENCE"],
  CAL: [
    "ASSOCIATE IN CONTACT CENTER SERVICES",
    "ASSOCIATE IN CUSTOMER SERVICE COMMUNICATION",
    "ASSOCIATE IN SYSTEM COMMUNICATIONS TECHNOLOGY",
    "BACHELOR IN PERFORMING ARTS",
    "BACHELOR INTEGRATED ARTS IN BROADCAST ART",
    "BACHELOR OF ARTS IN BROADCAST PRODUCTION",
    "BACHELOR OF ARTS IN COMMUNICATION & SERVICE MANAGEMENT",
    "BACHELOR OF ARTS IN CUSTOMER SERVICE COMMUNICATION",
    "BACHELOR OF ARTS IN ORGANIZATIONAL COMMUNICATION",
    "BACHELOR OF ARTS IN PERFORMING ARTS - DANCE",
    "BACHELOR OF ARTS IN PERFORMING ARTS - THEATER ARTS",
    "BACHELOR OF SCIENCE IN DIGITAL ARTS",
    "BACHELOR OF SCIENCE IN RADIO & TELEVISION",
    "CERTIFICATE IN DIGITAL ARTS",
    "ONE-YEAR PRE-BACCALAUREATE",
  ],
  COAHS: [
    "ASSOCIATE OF APPLIED SCIENCE IN PHARMACY TECHNOLOGY",
    "BACHELOR IN PHARMACEUTICAL MARKETING",
    "BACHELOR OF SCIENCE IN NURSING",
    "BACHELOR OF SCIENCE IN PHARMACY",
    "BACHELOR OF SCIENCE IN RADIOLOGIC TECHNOLOGY",
  ],
  CHK: [
    "ASSOCIATE IN DANCE INSTRUCTION AND DANCE SPORTS",
    "ASSOCIATE IN SPORTS COACHING",
    "BACHELOR IN PHYSICAL WELNESS",
    "BACHELOR IN PHYSICAL WELNESS- SPORTS MANAGEMENT",
    "BACHELOR OF SCIENCE IN EXERCISE AND SPORTS SCIENCE",
    "CERTIFICATE IN FOLK DANCING",
    "CERTIFICATE IN SPORTS OFFICIATING",
    "DIPLOMA IN SPORTS AND RECREATIONAL FACILITIES MANAGEMENT",
  ],
  CMLI: [
    "BACHELOR OF SCIENCE IN MARINE ENGINEERING",
    "BACHELOR OF SCIENCE IN MARINE ENGINEERING MARINE TRANSPORTATION",
    "DIPLOMA IN MARINE ENGINEERING",
    "DIPLOMA IN MARINE TRANSPORTATION",
  ],
  SOL: ["JURIS DOCTOR"],
};

var majors = {
  // CBFS
  "BACHELOR OF SCIENCE IN SECRETARIAL ADMINISTRATION": ["OFFICE MANAGEMENT"],

  "BACHELOR OF SCIENCE IN COMMERCE": ["MARKETING", "MANAGEMENT"],

  "BACHELOR OF SCIENCE IN MARKETING MANAGEMENT": ["RETAIL MANAGEMENT", " "],

  "BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION": [
    "MANAGEMENT",
    "PURCHASING AND SUPPLY CHAIN MANAGEMENT",
    "SUPPLY MANAGEMENT",
    "BUILDING AND PROPERTY MANAGEMENT",
    "HUMAN RESOURCE DEVELOPMENT MANAGEMENT",
  ],
  // CTHM
  "BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT": [
    "HOTEL AND RESTAURANT MANAGEMENT",
  ],
  // IGS/CGS/CCAPS
  "BACHELOR OF ARTS IN POLITICAL SCIENCE": [
    "LOCAL GOVERNMENT ADM (EXECUTIVE PROGRAM)",
  ],
  "DOCTOR IN EDUCATION": [
    "EDUCATIONAL MANAGEMENT",
    "INNOVATIVE EDUCATONAL MANAGEMENT",
  ],
  "DOCTOR OF PHILOSOPHY": ["SPECIAL EDUCATION"],

  "EXECUTIVE DOCTOR IN LEADERSHIP": ["BUSINESS", "EDUCATION"],

  "EXECUTIVE MASTER IN BUSINESS ADMINISTRATION": [
    "BUILDING PROPERTY MANAGEMENT",
    "ENTREPRENEURSHIP",
  ],
  "MASTER IN ARTS IN EDUCATION": [
    "ADMINISTRATION AND SUPERVISION",
    "EDUCATIONAL MANAGEMENT",
    "GUIDANCE AND COUNSELING",
    "INSTRUCTIONAL MEDIA DESIGN",
  ],
  "MASTER IN BUSINESS ADMINISTRATION": ["HEALTHCARE MANAGEMENT"],
  "MASTER IN INFORMATION SYSTEMS": [
    "INNOVATIVE TECHNOLOGY & ENTERPRISE MANAGEMENT",
  ],
  "MASTER OF ARTS IN NURSING": ["NURSING SERVICE ADMINISTRATION"],

  "MASTER OF SCIENCE IN RADIOLOGIC TECHNOLOGY": ["CLINICAL SUPERVISION"],

  // COS
  "BACHELOR OF SCIENCE IN PSYCHOLOGY": ["RESEARCH & MEASUREMENT", " "],

  "BACHELOR OF SCIENCE": ["BIOLOGICAL SCIENCE", "MATHEMATICS"],

  "BACHELOR OF ARTS": ["ENGLISH"],

  // COE
  "BACHELOR IN SECONDARY EDUCATION": [
    "BIOLOGICAL SCIENCE",
    "ENGLISH",
    "FILIPINO",
    "GENERAL SCIENCE",
    "MATHEMATICS",
    "SOCIAL STUDIES",
    "TECHNOLOGY AND LIVELIHOOD EDUCATION",
  ],
  "CERTIFICATE OF TEACHING ": ["HIGH SCHOOL", "ELEMENTARY"],

  // CCSCE
  "BACHELOR OF SCIENCE IN CIVIL ENGINEERING": [
    "CONSTRUCTION ENGINEERING MANAGEMENT",
  ],

  // IIT/COT/ITRED/CTM
  "ASSOCIATE IN INDUSTRIAL TECHNOLOGY": [
    "COMPUTER",
    "AUTOMOTIVE",
    "DRAFTING",
    "ELECTRICAL",
    "ELECTRONICS",
    "REFRIGERATION & AIR CONDITIONING",
  ],
  "BACHELOR OF SCIENCE IN INDUSTRIAL TECHNOLOGY": [
    "AUTOMOTIVE",
    "DRAFTING",
    "ELECTRICAL",
    "ELECTRONICS",
    "MACHINE SHOP",
    "REFRIGERATION & AIR CONDITIONING",
  ],
  "CERTIFICATE IN INDUSTRIAL TECHNOLOGY": [
    "AUTOMOTIVE",
    "DRAFTING",
    "ELECTRICAL",
    "ELECTRONICS",
    "MECHANICAL",
    "REFRIGERATION & AIR CONDITIONING",
  ],
  "DIPLOMA IN INDUSTRIAL FACILITIES TECHNOLOGY": ["SERVICE MECHANICS"],
  // CCIS
  "BACHELOR OF SCIENCE IN COMPUTER SCIENCE": [
    "APPLICATION DEVELOPMENT",
    "SOCIAL COMPUTING",
    "OBJECT-ORIENTED PROGRAMMING",
  ],
  "BACHELOR OF SCIENCE IN INDUSTRIAL TECHNOLOGY": ["COMPUTER"],
  "CERTIFICATE IN INDUSTRIAL TECHNOLOGY": ["COMPUTER"],
  // CGPP
  "BACHELOR OF ARTS IN  POLITICAL SCIENCE": [
    "LOCAL GOVERNMENT ADMINISTRATION",
    "PARALEGAL STUDIES",
    "POLICY MANAGEMENT",
  ],
  // CAL
  "BACHELOR IN PERFORMING ARTS ": ["MUSIC EDUCATION MINOR MUSIC PRODUCTION"],
  "BACHELOR OF SCIENCE IN DIGITAL ARTS": ["ANIMATION"],
  "BACHELOR OF SCIENCE IN RADIO & TELEVISION": ["BROADCASTING"],
  // COAHS

  // CHK
  "ASSOCIATE IN DANCE INSTRUCTION AND DANCE SPORTS": ["DANCE"],
  "BACHELOR OF SCIENCE IN EXERCISE AND SPORTS SCIENCE": [
    "FITNESS AND SPORTS MANAGEMENT",
  ],
  "CERTIFICATE IN SPORTS OFFICIATING": ["SPORTS"],
  // CMLI

  // SOL
};

department.addEventListener("change", function () {
  program.length = 1;
  major.length = 1;
  major.disabled = true;
  if (department.value === "") {
    program.disabled = true;
  } else {
    program.disabled = false;
    for (var i = 0; i < programs[department.value].length; i++) {
      var option = document.createElement("option");
      option.text = programs[department.value][i];
      program.add(option);
    }
  }
});

program.addEventListener("change", function () {
  major.length = 1;
  if (program.value === "") {
    major.disabled = true;
  } else {
    major.disabled = false;
    for (var i = 0; i < majors[program.value].length; i++) {
      var option = document.createElement("option");
      option.text = majors[program.value][i];
      major.add(option);
    }
  }
});
